### ISSUE TITLE
Error Getting Access Token for Service Account

### ISSUE THREAD

**Issue by ZonerDan** [Powerspace/pg2bq#5]
Hello again,

I'm setting GOOGLE_APPLICATION_CREDENTIALS and I have the same file it is referencing set within configuration.conf for gcloud service-account-key-path.  However, Im getting the following error:
"Exception in thread "main" com.google.cloud.bigquery.BigQueryException: Error getting access token for service account:"

I have admin permissions set on the only service account I have as admin for GCS and BigQuery.

**Comment by sderosiaux** [comment]
Hey,

Here it does not even try to validate the permission, it's failing before. It seems the client can't even contact Google to authenticate the token. Is it a transient error? if you try several times, do you always get the error? Is your key file a proper .json format (not P12) ?

**Comment by ZonerDan** [comment]
I’ve tried numerous times and always receive the error.  I did not modify the key file after it was generated.  All I did was place it on my server.  I’ve copied the content into an online json validator which has confirmed the content is valid.  The file extension is also .json.

**Comment by sderosiaux** [comment]
All right. 

Can you execute those commands and ensure it looks fine to you (particularly the key id should be the same you find in the `.json` you get, the project is good etc.)
```
$ gcloud iam service-accounts keys list --iam-account=<service>@<project>.iam.gserviceaccount.com
KEY_ID                                    CREATED_AT            EXPIRES_AT
...
$ gcloud iam service-accounts describe <service>@<project>.iam.gserviceaccount.com
```

Are you using an absolute path to refer to the file in your command ? (in `GAC=` and `configuration.conf`) ? Can you try `export GOOGLE_APPLICATION_CREDENTIALS=/path/to/xxx.json` then launch pg2bq ?

Not quite sure where to look, sorry. ;-)

**Comment by ZonerDan** [comment]
Only oddity I see is that list returns 4 keys and I only see one when viewing the service account in the Google Cloud Console.  When attempting to delete any of the other 3 keys I get this error:  ERROR: (gcloud.beta.iam.service-accounts.keys.delete) INVALID_ARGUMENT: Request contains an invalid argument.  The syntax of my command matches what is documented at https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/keys/delete  I havent found any posts or stackoverflow articles discussing this error.

**Comment by ZonerDan** [comment]
After multiple tweaks I now no longer receive the token related error but instead receive a new error:  cloud.bigquery.BigQueryException: Connection refused or sometimes it shows the following:
aused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
{
  "code" : 401,
  "errors" : [ {
    "domain" : "global",
    "location" : "Authorization",
    "locationType" : "header",
    "message" : "Login Required",
    "reason" : "required"
  } ],
  "message" : "Login Required"
}

**Comment by kcaraujotech** [comment]
I'm getting this error too

Exception in thread "main" com.google.cloud.bigquery.BigQueryException: Error getting access token for service account: 400 Bad Request
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT Signature."
}
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:106)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:206)
	at com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:319)
	at com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:316)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:315)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:290)
Caused by: java.io.IOException: Error getting access token for service account: 400 Bad Request

Everything is fine with service account and it is as "Owner" but I'm getting this error.
